server:
  port: 31500
spring:
  application:
    name: xc-service-filesystem
#mongo配置
  data:
    mongodb:
      database: mooc_filesystem
      uri: mongodb://127.0.0.1:27017
#SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB
itmooc:
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: UTF-8
    tracker_servers: 192.168.14.129:22122 #多个 trackerServer中间以逗号分隔

#Eureka配置 客户端：注册和发现功能
#eureka:
#  client:
#    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
#    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息
#    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
#      defaultZone: ${EUREKA_SERVER:http://eureka01:50101/eureka/,http://eureka02:50102/eureka/}
# instance:
#    prefer-ip-address: true #将自己的id地址注册到Eureka服务中
#    ip-address: ${IP_ADDRESS:127.0.0.1}
#    instance-id: ${spring.application.name}:${server.port} #指定实例id