server:
  port: 31500
spring:
  application:
    name: it-service-media-processor
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: mooc_media
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
it-service-media:
  mq:
    routingkey-media-video: routingkey_media_video
  video-location: F:/ITMooc/video/
  ffmpeg-path: D:/Program Files/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe